[package]
name = "hopter_friend"
version = "0.1.0"
edition = "2021"

[dependencies]
crc32fast = { version = "1.4.2", default-features = false }
crossbeam = "0.8.4"
goblin = "0.8.2"
hadusos = "0.2.1"
libc = "0.2.155"
static_assertions = "1.1.0"
